### ISSUE TITLE
Question... Is it possible to have it auto attach?

### ISSUE THREAD

**Issue by codingforfreeandme** [karpach/debug-attach-manager#14]
I love this extension and use it constantly with dot net watch run

Has anyone figured out a way to have it auto re-attach everytime so I dont have to keep pressing control-shift-alt-f5 after every code change?

**Comment by mlafleur** [comment]
This would be an excellent addition. Ideally it would also support re-attach when debugging tests. This could allow debugging both integration tests and the service(s) they're calling into without multiple copies of Visual Studio or breakpoints.

**Comment by karpach** [comment]
I currently not planning to add auto re-attach functionality. See if VS built-in edit and continue functionality works for your case: 

https://learn.microsoft.com/en-us/visualstudio/debugger/edit-and-continue?view=vs-2022
