### ISSUE TITLE
Selected processes are not running. Try to run your application first.

### ISSUE THREAD

**Issue by horacioj** [karpach/debug-attach-manager#15]
I'm using this extension since long time ago and I love it.

Since some months ago, I'm unable to use it. 
The web site, is running., but when I click on "Attach Smart Debug Selections" I get a modal error dialog with title "Debug Attach History Error", and message "Selected processes are not running. Try to run your application first."
![debug-attach-error](https://user-images.githubusercontent.com/984821/119413235-9e92d680-bcc3-11eb-8cfb-7b8f8b290492.jpg)

This happens e.g. on .NET 'traditional' (web app). It doesn't happen on .NET core apps.

Any ideas?

**Comment by karpach** [comment]
Hi,

Try to remove the selected process from the bottom list and re-add it.

**Comment by horacioj** [comment]
Thanks! Removing and adding again processes from the list solved the problem.
