### ISSUE TITLE
Small improvements

### ISSUE THREAD

**Issue by NN---** [karpach/debug-attach-manager#2]
1. Make dropdoown box with recent servers I connected to
2. Make connection box bigger.

**Comment by karpach** [comment]
What do you mean by "make connection box bigger"?

**Comment by NN---** [comment]
Wow, a year passed. I need to install the extension again to see the problem :)
I think I meant this window https://github.com/karpach/debug-attach-manager/blob/master/Screenshots/screenshot7.png

**Comment by karpach** [comment]
Why does it need to be bigger? Is it text box for the server is too small?

**Comment by karpach** [comment]
I am adding a few features to the extension and why I am there I decided to address open issues.

**Comment by NN---** [comment]
I'll install and update you if there are any issues .

**Comment by karpach** [comment]
There are no comments for the past 2 years.
