### ISSUE TITLE
VSIX not contains License

### ISSUE THREAD

**Issue by VladSnap** [karpach/debug-attach-manager#3]
Microsoft.VisualStudio.ExtensionManager.MissingPackagePartException: The package does not contain a license agreement, weapons in the manifest expansion (ru-RU/../Ms-PL.rtf).

RUS:
Microsoft.VisualStudio.ExtensionManager.MissingPackagePartException: В пакете не содержится лицензионное соглашение, указанное в манифесте расширения (ru-RU/../Ms-PL.rtf).

**Comment by karpach** [comment]
Strange, they manifest is there. I'll check. Thank you for reporting.

RUS:
Спасибо, я проверю.

**Comment by karpach** [comment]
I added the license to the git repository and to the extension.
