### ISSUE TITLE
Fail on install to Visual Studio 2019 Preview 2.0

### ISSUE THREAD

**Issue by baltika10** [karpach/debug-attach-manager#4]
Installation log is attached

[dd_VSIXInstaller_20190128092750.log](https://github.com/karpach/debug-attach-manager/files/2801846/dd_VSIXInstaller_20190128092750.log)

**Comment by baltika10** [comment]
https://blogs.msdn.microsoft.com/visualstudio/2018/09/26/how-to-upgrade-extensions-to-support-visual-studio-2019/

Need just to update source.extension.vsixmanifest

**Comment by CADbloke** [comment]
Fails on release version  16.0.0 - same thing - Microsoft.VisualStudio.Component.CoreEditor

**Comment by otebos** [comment]
I've created Pull request with a fix
If you cannot wait you can for my branch and build extension for yourself
https://github.com/otebos/debug-attach-manager/tree/VS2019-manifest-update

**Comment by MisterY** [comment]
![image](https://user-images.githubusercontent.com/462445/56035098-7d600d80-5d29-11e9-8d04-25eb0cc0bfad.png)

with the currently published version. But with 

![image](https://user-images.githubusercontent.com/462445/56035123-910b7400-5d29-11e9-9976-43861957acda.png)

everything seem to work.

**Comment by chasingcode** [comment]
The Microsoft.VisualStudio.Component.CoreEditor prerequisite in the vsixmanifest should have an open-ended upper bound according to Mads Kristensen:
https://devblogs.microsoft.com/visualstudio/how-to-upgrade-extensions-to-support-visual-studio-2019/
After I edited that file locally, I was successfully able to install the extension in VS2019 Community.

**Comment by gonziii** [comment]
@chasingcode Where did you find the vsixmanifest? There are many vsixmanifest.

**Comment by chasingcode** [comment]
Thank you for merging the PR. When you have time, can you update the extension on the Visual Studio Marketplace?

**Comment by karpach** [comment]
I just updated the extension in Marketplace.
